---
- name: Deploy e-commerce application
  hosts: web
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    repo_url: "https://github.com/Riahisemah/Lab-infra-aws.git"

  tasks:
    - name: Install required packages
      dnf:
        name: [docker, git]
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Force docker group refresh
      shell: sg docker -c "true"
      become_user: ec2-user
      ignore_errors: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "0755"

    - name: Remove old app directory if exists
      file:
        path: /opt/ecommerce
        state: absent

    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: /opt/ecommerce
        version: main
        force: yes
      become_user: ec2-user

    - name: Build and start containers
      shell: |
        cd /opt/ecommerce
        sg docker -c "/usr/local/bin/docker-compose up -d --build --force-recreate"
      become_user: ec2-user

    - name: Wait for app to be healthy
      uri:
        url: http://localhost/health
        status_code: 200
      retries: 15
      delay: 10
      register: result
      until: result.status == 200

    - name: Show running containers
      shell: |
        cd /opt/ecommerce
        sg docker -c "/usr/local/bin/docker-compose ps"
      become_user: ec2-user
      register: ps

    - debug:
        msg: "{{ ps.stdout_lines }}"
