# ============================================================
# inventory.ini — for MANUAL testing only
# In the CI/CD pipeline, this file is generated automatically
# from Terraform output IPs.
# ============================================================

[web]

[web:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
